// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcoqqqpbuzwtsjbwlnyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjb3FxcXBidXp3dHNqYndsbnl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjg5MDksImV4cCI6MjA2ODg0NDkwOX0.bGx7WFNtV6iA0ep4iNwq_vqUIub0YO38RYRFsB0npWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});